apiVersion: v1
kind: Service
metadata:
  name: prod-deployment-service
  namespace: dev
spec:
  type: LoadBalancer
  selector:
    app: dev-app
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080